<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.wildedit</groupId>
    <artifactId>langEditor</artifactId>
    <version>0.1-MVP</version>

    <licenses>
        <license>
            <name>AGPL-3.0-only</name>
            <url>https://spdx.org/licenses/AGPL-3.0-only.html</url>
            <distribution>repo</distribution>
            <comments>Just be nice about it if you want to use it</comments>
        </license>
    </licenses>

    <dependencies>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.20.0</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>21.0.9</version>
        </dependency>
        <!--  Gson: Java to JSON conversion -->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.13.2</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <configuration>
                    <mainClass>org.wildedit.Main</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.7.6</version>
                <executions>
                    <execution>
                        <id>bundling-for-windows</id>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <mainClass>org.wildedit.Main</mainClass>
                            <bundleJre>true</bundleJre>
                            <platform>windows</platform>
                            <createZipball>true</createZipball>
                        </configuration>
                    </execution>
<!--                    <execution>-->
<!--                        <id>bundling-for-linux</id>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>package</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <platform>linux</platform>-->
<!--                            <createTarball>true</createTarball>-->
<!--                            <jdkPath>X:\\path\to\linux\jdk</jdkPath>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                    <execution>-->
<!--                        <id>bundling-for-mac</id>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>package</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <platform>mac</platform>-->
<!--                            <createTarball>true</createTarball>-->
<!--                            <jdkPath>X:\\path\to\mac\jdk</jdkPath>-->
<!--                        </configuration>-->
<!--                    </execution>-->
                </executions>
            </plugin>
        </plugins>

    </build>

</project>